In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [ ]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

## Read data from CSV files

In [ ]:
df = pd.read_csv('train.csv')

In [ ]:
df.head(10)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   
5            6         0       3   
6            7         0       1   
7            8         0       3   
8            9         1       3   
9           10         1       2   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   
5                                   Moran, Mr. James    male   NaN      0   
6                            McCarthy, Mr. Timothy J    male  54.0      0   
7                     Palsson, Master. Gosta Leonard    male   2.0      3   
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S  
5      0            330877   8.4583   NaN        Q  
6      0             17463  51.8625   E46        S  
7      1            349909  21.0750   NaN        S  
8      2            347742  11.1333   NaN        S  
9      0            237736  30.0708   NaN        C

## Exploratory Data Analysis

In [ ]:
df.shape

(891, 12)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [ ]:
df.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [ ]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [ ]:
df = df.dropna(subset=['Embarked'])

In [ ]:
df['Cabin'].unique()

array([nan, 'C85', 'C123', 'E46', 'G6', 'C103', 'D56', 'A6',
       'C23 C25 C27', 'B78', 'D33', 'B30', 'C52', 'C83', 'F33', 'F G73',
       'E31', 'A5', 'D10 D12', 'D26', 'C110', 'B58 B60', 'E101', 'F E69',
       'D47', 'B86', 'F2', 'C2', 'E33', 'B19', 'A7', 'C49', 'F4', 'A32',
       'B4', 'B80', 'A31', 'D36', 'D15', 'C93', 'C78', 'D35', 'C87',
       'B77', 'E67', 'B94', 'C125', 'C99', 'C118', 'D7', 'A19', 'B49',
       'D', 'C22 C26', 'C106', 'C65', 'E36', 'C54', 'B57 B59 B63 B66',
       'C7', 'E34', 'C32', 'B18', 'C124', 'C91', 'E40', 'T', 'C128',
       'D37', 'B35', 'E50', 'C82', 'B96 B98', 'E10', 'E44', 'A34', 'C104',
       'C111', 'C92', 'E38', 'D21', 'E12', 'E63', 'A14', 'B37', 'C30',
       'D20', 'B79', 'E25', 'D46', 'B73', 'C95', 'B38', 'B39', 'B22',
       'C86', 'C70', 'A16', 'C101', 'C68', 'A10', 'E68', 'B41', 'A20',
       'D19', 'D50', 'D9', 'A23', 'B50', 'A26', 'D48', 'E58', 'C126',
       'B71', 'B51 B53 B55', 'D49', 'B5', 'B20', 'F G63', 'C62 C64',
       'E24',

In [ ]:
df['Ticket'].unique()

array(['A/5 21171', 'PC 17599', 'STON/O2. 3101282', '113803', '373450',
       '330877', '17463', '349909', '347742', '237736', 'PP 9549',
       '113783', 'A/5. 2151', '347082', '350406', '248706', '382652',
       '244373', '345763', '2649', '239865', '248698', '330923', '113788',
       '347077', '2631', '19950', '330959', '349216', 'PC 17601',
       'PC 17569', '335677', 'C.A. 24579', 'PC 17604', '113789', '2677',
       'A./5. 2152', '345764', '2651', '7546', '11668', '349253',
       'SC/Paris 2123', '330958', 'S.C./A.4. 23567', '370371', '14311',
       '2662', '349237', '3101295', 'A/4. 39886', 'PC 17572', '2926',
       '113509', '19947', 'C.A. 31026', '2697', 'C.A. 34651', 'CA 2144',
       '2669', '36973', '347088', 'PC 17605', '2661', 'C.A. 29395',
       'S.P. 3464', '3101281', '315151', 'C.A. 33111', 'S.O.C. 14879',
       '2680', '1601', '348123', '349208', '374746', '248738', '364516',
       '345767', '345779', '330932', '113059', 'SO/C 14885', '3101278',
       'W./C

In [ ]:
df = df.drop(columns=["Cabin", "Name", "Ticket"], axis=1)

In [ ]:
df.sample(n=10)

PassengerId  Survived  Pclass     Sex   Age  SibSp  Parch      Fare  \
398          399         0       2    male  23.0      0      0   10.5000   
363          364         0       3    male  35.0      0      0    7.0500   
883          884         0       2    male  28.0      0      0   10.5000   
475          476         0       1    male   NaN      0      0   52.0000   
610          611         0       3  female  39.0      1      5   31.2750   
314          315         0       2    male  43.0      1      1   26.2500   
638          639         0       3  female  41.0      0      5   39.6875   
498          499         0       1  female  25.0      1      2  151.5500   
334          335         1       1  female   NaN      1      0  133.6500   
726          727         1       2  female  30.0      3      0   21.0000   

    Embarked  
398        S  
363        S  
883        S  
475        S  
610        S  
314        S  
638        S  
498        S  
334        S  
726        S

In [ ]:
median_age = df['Age'].median()
df['Age'].fillna(median_age, inplace=True)

## CatBoost

In [ ]:
!pip install catboost

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.2/98.2 MB 10.7 MB/s eta 0:00:00


In [ ]:
X = df.iloc[:, 2:].values
y = df.iloc[:, 1].values

In [ ]:
X

array([[3, 'male', 22.0, ..., 0, 7.25, 'S'],
       [1, 'female', 38.0, ..., 0, 71.2833, 'C'],
       [3, 'female', 26.0, ..., 0, 7.925, 'S'],
       ...,
       [3, 'female', 28.0, ..., 2, 23.45, 'S'],
       [1, 'male', 26.0, ..., 0, 30.0, 'C'],
       [3, 'male', 32.0, ..., 0, 7.75, 'Q']], dtype=object)

In [ ]:
y

array([0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 18)

### Train the model

In [ ]:
import catboost as cb

cat_features = [1, 6]
model = cb.CatBoostClassifier(cat_features=cat_features, verbose=100)

In [ ]:
model.fit(X_train, y_train)

Learning rate set to 0.008906
0:	learn: 0.6873629	total: 62.3ms	remaining: 1m 2s
100:	learn: 0.4544255	total: 661ms	remaining: 5.88s
200:	learn: 0.4002628	total: 1.23s	remaining: 4.89s
300:	learn: 0.3760790	total: 1.66s	remaining: 3.86s
400:	learn: 0.3579534	total: 2.33s	remaining: 3.47s
500:	learn: 0.3449624	total: 3.17s	remaining: 3.16s
600:	learn: 0.3343603	total: 3.63s	remaining: 2.41s
700:	learn: 0.3231663	total: 4.86s	remaining: 2.07s
800:	learn: 0.3135066	total: 6.17s	remaining: 1.53s
900:	learn: 0.3046173	total: 7.36s	remaining: 809ms
999:	learn: 0.2945806	total: 8.7s	remaining: 0us


In [ ]:
y_pred = model.predict(X_test)

## Confusion Matrix

In [ ]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[101,   8],
       [ 19,  50]])

## The four metrics

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.848314606741573

In [ ]:
from sklearn.metrics import precision_score, recall_score, f1_score

precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

print(f"Precision: {precision}")
print(f"Recall: {recall}")
print(f"F1 Score: {f1}")

Precision: 0.8620689655172413
Recall: 0.7246376811594203
F1 Score: 0.7874015748031497


In [17]:
params = model.get_all_params()
params

{'nan_mode': 'Min',
 'eval_metric': 'Logloss',
 'combinations_ctr': ['Borders:CtrBorderCount=15:CtrBorderType=Uniform:TargetBorderCount=1:TargetBorderType=MinEntropy:Prior=0/1:Prior=0.5/1:Prior=1/1',
  'Counter:CtrBorderCount=15:CtrBorderType=Uniform:Prior=0/1'],
 'iterations': 1000,
 'sampling_frequency': 'PerTree',
 'fold_permutation_block': 0,
 'leaf_estimation_method': 'Newton',
 'random_score_type': 'NormalWithModelSizeDecrease',
 'counter_calc_method': 'SkipTest',
 'grow_policy': 'SymmetricTree',
 'penalties_coefficient': 1,
 'boosting_type': 'Plain',
 'model_shrink_mode': 'Constant',
 'feature_border_type': 'GreedyLogSum',
 'ctr_leaf_count_limit': 18446744073709551615,
 'bayesian_matrix_reg': 0.10000000149011612,
 'one_hot_max_size': 2,
 'eval_fraction': 0,
 'force_unit_auto_pair_weights': False,
 'l2_leaf_reg': 3,
 'random_strength': 1,
 'rsm': 1,
 'boost_from_average': False,
 'max_ctr_complexity': 4,
 'model_size_reg': 0.5,
 'simple_ctr': ['Borders:CtrBorderCount=15:CtrBorder

## Grid Search

In [ ]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = model,
                             X = X,
                             y = y,
                             scoring = 'accuracy',
                             cv = 10)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

Learning rate set to 0.009366
0:	learn: 0.6873352	total: 6.89ms	remaining: 6.89s
100:	learn: 0.4364213	total: 492ms	remaining: 4.38s
200:	learn: 0.3843362	total: 1.14s	remaining: 4.52s
300:	learn: 0.3631493	total: 1.89s	remaining: 4.38s
400:	learn: 0.3510188	total: 2.71s	remaining: 4.05s
500:	learn: 0.3398625	total: 3.43s	remaining: 3.42s
600:	learn: 0.3289797	total: 4.24s	remaining: 2.81s
700:	learn: 0.3178125	total: 4.96s	remaining: 2.12s
800:	learn: 0.3067745	total: 5.91s	remaining: 1.47s
900:	learn: 0.2946588	total: 6.98s	remaining: 767ms
999:	learn: 0.2838067	total: 8.12s	remaining: 0us
Learning rate set to 0.009366
0:	learn: 0.6870695	total: 19.6ms	remaining: 19.6s
100:	learn: 0.4414611	total: 1.24s	remaining: 11s
200:	learn: 0.3916405	total: 2.41s	remaining: 9.57s
300:	learn: 0.3724780	total: 3.23s	remaining: 7.51s
400:	learn: 0.3589219	total: 4.31s	remaining: 6.43s
500:	learn: 0.3466906	total: 5.12s	remaining: 5.1s
600:	learn: 0.3371375	total: 5.87s	remaining: 3.9s
700:	learn: 

In [ ]:
from sklearn.model_selection import GridSearchCV
parameters = [{'learning_rate': [0.001,0.005,0.01], 'depth': [4,7,10], 'l2_leaf_reg': [2,6,10], 'random_strength': [0,5,10]}]
grid_search = GridSearchCV(estimator = model,
                           param_grid = parameters,
                           scoring = 'accuracy',
                           cv = 10)
grid_search.fit(X, y)
best_accuracy = grid_search.best_score_
best_parameters = grid_search.best_params_
print("Best Accuracy: {:.2f} %".format(best_accuracy*100))
print("Best Parameters:", best_parameters)

Streaming output truncated to the last 5000 lines.
700:	learn: 0.3648662	total: 2.69s	remaining: 1.15s
800:	learn: 0.3537682	total: 3.21s	remaining: 799ms
900:	learn: 0.3392073	total: 3.81s	remaining: 418ms
999:	learn: 0.3237839	total: 4.2s	remaining: 0us
0:	learn: 0.6870192	total: 3.57ms	remaining: 3.56s
100:	learn: 0.4901179	total: 258ms	remaining: 2.29s
200:	learn: 0.4391038	total: 494ms	remaining: 1.96s
300:	learn: 0.4089127	total: 740ms	remaining: 1.72s
400:	learn: 0.3944507	total: 967ms	remaining: 1.44s
500:	learn: 0.3816161	total: 1.22s	remaining: 1.22s
600:	learn: 0.3723215	total: 1.47s	remaining: 976ms
700:	learn: 0.3627778	total: 1.7s	remaining: 727ms
800:	learn: 0.3537599	total: 1.95s	remaining: 485ms
900:	learn: 0.3390635	total: 2.23s	remaining: 245ms
999:	learn: 0.3184424	total: 2.56s	remaining: 0us
0:	learn: 0.6910763	total: 2.44ms	remaining: 2.44s
100:	learn: 0.4867396	total: 251ms	remaining: 2.24s
200:	learn: 0.4433750	total: 486ms	remaining: 1.93s
300:	learn: 0.4178851

## Bayesian Optimization

In [18]:
!pip install scikit-optimize

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 107.8/107.8 kB 4.6 MB/s eta 0:00:00


In [20]:
from skopt import BayesSearchCV
from skopt.space import Real, Integer, Categorical

param_space = {
    'learning_rate': Real(0.0001, 0.1, prior='log-uniform'),
    'depth': Integer(4, 12),
    'l2_leaf_reg': Integer(2, 15),
    'random_strength': Integer(0, 15),
    'iterations': Integer(100, 500),
    'bagging_temperature': Real(0, 1),
    'border_count': Integer(32, 100),
    'colsample_bylevel': Real(0.5, 1.0)
}

opt = BayesSearchCV(
    estimator=model,
    search_spaces=param_space,
    n_iter=50,
    scoring='accuracy',
    cv=10,
    n_jobs=-1,
    random_state=18
)

opt.fit(X, y)

best_accuracy = opt.best_score_
best_parameters = opt.best_params_

print("Best Accuracy: {:.2f} %".format(best_accuracy * 100))
print("Best Parameters:", best_parameters)

0:	learn: 0.6910777	total: 27ms	remaining: 11.1s
100:	learn: 0.5335526	total: 1.65s	remaining: 5.1s
200:	learn: 0.4368832	total: 3.22s	remaining: 3.41s
300:	learn: 0.3751069	total: 4.79s	remaining: 1.8s
400:	learn: 0.3332368	total: 6.36s	remaining: 206ms
413:	learn: 0.3289864	total: 6.55s	remaining: 0us
Best Accuracy: 83.92 %
Best Parameters: OrderedDict([('bagging_temperature', 0.011837941798665057), ('border_count', 93), ('colsample_bylevel', 0.714666818334899), ('depth', 12), ('iterations', 414), ('l2_leaf_reg', 2), ('learning_rate', 0.0023607694336395878), ('random_strength', 0)])


## Choose either

In [46]:
model = cb.CatBoostClassifier(cat_features=cat_features, verbose=100, depth=10, l2_leaf_reg=10, learning_rate=0.005, random_strength=0)
model.fit(X_train, y_train)

0:	learn: 0.6912638	total: 34.5ms	remaining: 14.2s
100:	learn: 0.5387668	total: 3.6s	remaining: 11.2s
200:	learn: 0.4423523	total: 6.03s	remaining: 6.39s
300:	learn: 0.3795799	total: 7.72s	remaining: 2.9s
400:	learn: 0.3366886	total: 9.31s	remaining: 302ms
413:	learn: 0.3322221	total: 9.51s	remaining: 0us


In [ ]:
model = cb.CatBoostClassifier(cat_features=cat_features, verbose=100, **best_parameters)
model.fit(X_train, y_train)

## Predict survivial for the test data

In [21]:
df_test = pd.read_csv('test.csv')
df_test.head(5)

PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  
0  34.5      0      0   330911   7.8292   NaN        Q  
1  47.0      1      0   363272   7.0000   NaN        S  
2  62.0      0      0   240276   9.6875   NaN        Q  
3  27.0      0      0   315154   8.6625   NaN        S  
4  22.0      1      1  3101298  12.2875   NaN        S

### Data cleaning

In [22]:
df_test.isnull().sum()

PassengerId      0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [23]:
df_test = df_test.drop(columns=["Cabin", "Name", "Ticket"], axis=1)

In [24]:
median_age = df_test['Age'].median()
df_test['Age'].fillna(median_age, inplace=True)

In [25]:
median_fare = df_test['Fare'].median()
df_test['Fare'].fillna(median_fare, inplace=True)

In [26]:
df_test.head(5)

PassengerId  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0          892       3    male  34.5      0      0   7.8292        Q
1          893       3  female  47.0      1      0   7.0000        S
2          894       2    male  62.0      0      0   9.6875        Q
3          895       3    male  27.0      0      0   8.6625        S
4          896       3  female  22.0      1      1  12.2875        S

# Predict

In [42]:
X_test = df_test.iloc[:, 1:].values

In [47]:
y_pred = model.predict(X_test)

In [48]:
output = pd.DataFrame({'PassengerId': df_test.iloc[:, 0].values, 'Survived': y_pred})
output.to_csv('submission.csv', index=False)